name: Check formatting

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

concurrency:
  group: check-formatting-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: apt-get update
        run: sudo apt-get update

      - name: Install clang-format
        run: sudo apt-get -y install dos2unix

      - name: Check formatting
        uses: DoozyX/clang-format-lint-action@v0.18
        with:
          source: "./src ./tests"
          extensions: "hpp,cpp"
          clangFormatVersion: 16

      - name: Check line-endings
        run: ./scripts/check-line-endings.sh

      - name: Check formatting with Prettier
        uses: actionsx/prettier@v3
        with:
          # prettier CLI arguments.
          args: --write .
      - name: Show Prettier diff
        run: git --no-pager diff --exit-code --color=never
        shell: bash
